### ISSUE TITLE
[Feature discussion] Readme generator

### ISSUE THREAD

**Issue by ThijsZijdel** [fosslife/devtools-x#94]
## Todo before PR 

- [x] Setup `templates`
- [x] Preview final rendering 
- [x] Show/hide editor/ preview
- [x] Edit a part
- [x] Reordering parts
- [x] Removing parts
- [x] Preview `templates` before inserting
- [ ] Build more advanced templates like [Awsome Readme](https://github.com/matiassingers/awesome-readme)

## Todo for the `markdown editor` used in both modules
- [ ] Markdown cheatsheet
- [ ] → via one click insertion 
- [ ] Wordcount
- [ ] Emoji modal 

![Screenshot 2024-08-10 at 13 26 47](https://github.com/user-attachments/assets/d93bdccf-0597-4103-b86f-866e19c86115)

_Inspired by: [readme.so](https://readme.so/editor)_

## Ideas/ discussion

- Implement ai/ content writing? 
- Build a better ui for ["shields.io/badges"](https://shields.io/badges)
- Store references to local/machine files? ...

**Comment by Sparkenstein** [comment]
I am against any AI embedding mostly. It deserves it's own dedicated tool. we can support this globally by asking user to point to locally installed ollama version. but that's a big development decision, we should refrain for now

Maybe you can add a markdown cheatsheet. or even insert snippet option for example a lot of time I don't know what is the syntax for a table. https://github.github.com/gfm/ covers all 

Showing wordcount might help writers too (that's why it's called as markdown preview and not readme preview, it's generic).

and maybe emoji modal to easily copy paste emojis.

**Comment by ThijsZijdel** [comment]
> I am against any AI embedding mostly. It deserves it's own dedicated tool. we can support this globally by asking user to point to locally installed ollama version. but that's a big development decision, we should refrain for now

What about OpenAi key insert field? Just like the github pastebin

> Maybe you can add a markdown cheatsheet. or even insert snippet option for example a lot of time I don't know what is the syntax for a table. https://github.github.com/gfm/ covers all

Good call, will add a popover on the markdown editor & this new readme one.

> Showing wordcount might help writers too (that's why it's called as markdown preview and not readme preview, it's generic).

Will do, both are currently using the same MarkdownEditor under the hood. So it's an easy addition.

Primary difference of this "new" readme editor is the insertion of templates and the way the data is structured.

Each `section / part` is based on a `template` which auto combines to a default Markdown editor file.

> and maybe emoji modal to easily copy paste emojis.

For sure.

**Comment by Sparkenstein** [comment]
Yeah Openai key works. it should be completely optional. i.e. it doens't break any feature if the key is not present. 

(my bad I misunderstood that you renamed the existing markdown preview to Readme. this looks like a new module, that's great)

**Comment by ThijsZijdel** [comment]
Created a PR, have most of the MD features local ready.
But those still need some work, same for the color wheels 🔥

**Comment by Sparkenstein** [comment]
I think importing the readme doesnt populate the source, can you check

**Comment by ThijsZijdel** [comment]
Closing this for now and opening a general "md" extensions one.
